feat: add container build and run

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -12,7 +12,7 @@ on:
   workflow_dispatch:
 
 jobs:
-  test:
+  unit-and-integration-tests:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
@@ -34,3 +34,33 @@ jobs:
 
       - name: Run integration tests
         run: uv run pytest tests/integration
+
+  container-tests:
+    needs: unit-and-integration-tests
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v6
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v4
+
+      - name: Build Docker image
+        run: docker build -t events-api:test .
+
+      - name: Start container
+        run: docker run -d -p 5000:5000 --name events-api-test events-api:test
+
+      - name: Wait for container to be healthy
+        run: |
+          for i in (1..10); do
+            if curl -sf http://localhost:5000/api/health; then
+              echo "App in container is ready."
+              exit 0
+            fi
+            sleep 2
+          done
+          echo "App in container failed."
+          docker logs events-api-test
+          exit 1
+
