feat: add render-deployment job, extend README

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -4,11 +4,11 @@ on:
   push:
     branches:
       - main
-      - feature-continous-integration
+      - feature-continuous-deployment
   pull_request:
     branches:
       - main
-      - feature-continous-integration
+      - feature-continuous-deployment
   workflow_dispatch:
 
 jobs:
@@ -42,9 +42,6 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v6
 
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v4
-
       - name: Build Docker image
         run: docker build -t events-api:test .
 
@@ -53,7 +50,7 @@ jobs:
 
       - name: Wait for container to be healthy
         run: |
-          for i in {1..10}; do
+          for i in {1..20}; do
             if curl -sf http://localhost:5000/api/health; then
               echo "App in container is ready."
               exit 0
@@ -86,4 +83,38 @@ jobs:
           docker stop events-api-test || true
           docker rm events-api-test || true
 
+  render-deployment:
+    needs: container-tests
+    runs-on: ubuntu-latest
+    environment: production
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v6
 
+      - name: Log in to Docker Hub
+        uses: docker/login-action@v3
+        with:
+          username: ${{ env.DOCKER_HUB_USER }}
+          password: ${{ secrets.DOCKER_HUB_TOKEN }}
+
+      - name: Build Docker image
+        run: docker build -t ${{ env.DOCKER_HUB_USER }}/events-api:latest .
+
+      - name: Push Docker image
+        run: docker push ${{ env.DOCKER_HUB_USER }}/events-api:latest
+
+      - name: Trigger deploy webhook
+        run: |
+          curl ${{ secrets.RENDER_DEPLOY_HOOK }}
+
+      - name: Wait for service to be healthy
+        run: |
+          for i in {1..40}; do
+            if curl -sf https://${{ env.RENDER_BASE_URL }}/api/health; then
+              echo "API is healthy."
+              exit 0
+            fi
+            sleep 3
+          done
+          echo "Deployment failed."
+          exit 1
